apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # Horizontal pod autoscaler for the Terry Delmonaco AI service
  name: terry-delmonaco-ai
  namespace: terry-delmonaco-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: terry-delmonaco-ai
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70