name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
      - name: Lint & security
        run: |
          pre-commit run --all-files
      - name: Run tests
        run: pytest -q
      - name: Build Docker image
        # Build and tag the image for the new combined codebase
        run: docker build -t terry-delmonaco-presents-ai:1.0.0 .
