environment: dev
database_url: sqlite:///workflows.db
primary_endpoint: remote
llm_endpoints:
  local1:
    base_url: http://127.0.0.1:11434/v1
    model: qwen2.5:7b
    api_key_env: ""
  remote:
    base_url: https://generativelanguage.googleapis.com/v1beta/openai
    model: gemini-1.5-flash
    api_key_env: GOOGLE_API_KEY
