version: "3.9"
services:
  api:
    # Updated image name and tag to reflect the new combined codebase.
    image: terry-delmonaco-presents-ai:1.0.0
    build: .
    environment:
      - ENV=prod
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    restart: unless-stopped
